from django.urls import path
from dashboard import views
from views import onboarding as onboarding_views

urlpatterns = [
    path("dashboard/", views.dashboard_view, name="dashboard"),
    path("chat/", views.chat_view, name="chat"),
    path("portfolio/", views.portfolio_view, name="portfolio"),
    path("portfolio/upload/", views.portfolio_upload, name="portfolio_upload"),
    path("portfolio/xray/", views.portfolio_xray_view, name="portfolio_xray"),
    path("portfolio/refresh-navs/", views.portfolio_refresh_navs, name="portfolio_refresh_navs"),
    path("health/", views.health_view, name="health"),
    path("health/htmx/", views.health_htmx, name="health_htmx"),
    path("fire/", views.fire_view, name="fire"),
    path("tax/", views.tax_view, name="tax"),
    path("budget/", views.budget_view, name="budget"),
    path("goals/", views.goals_view, name="goals"),
    path("stress-test/", views.stress_test_view, name="stress_test"),
    path("api/stress-test/run/", views.stress_test_run_api, name="stress_test_run"),
    path("settings/", views.settings_view, name="settings"),
    path("settings/assumptions/", views.assumptions_view, name="settings_assumptions"),
    path("onboarding/", views.onboarding_view, name="onboarding"),
    path("onboarding/wizard/", onboarding_views.onboarding_wizard_view, name="onboarding_wizard"),
    path(
        "onboarding/step/<int:step_number>/",
        onboarding_views.onboarding_step_view,
        name="onboarding_step",
    ),
    path(
        "onboarding/save-step/<int:step_number>/",
        onboarding_views.onboarding_save_step_view,
        name="onboarding_save_step",
    ),
    path("onboarding/resume/", onboarding_views.onboarding_resume_view, name="onboarding_resume"),
    path("notifications/", views.notifications_view, name="notifications"),
    path("export/", views.export_reports_view, name="export_reports"),
    # New pages
    path("couples/", views.couples_view, name="couples"),
    path("sip-calculator/", views.sip_calculator_view, name="sip_calculator"),
    path("market-pulse/", views.market_pulse_view, name="market_pulse"),
    path("market-pulse/htmx/", views.market_pulse_htmx, name="market_pulse_htmx"),
    path("tax-copilot/", views.tax_copilot_view, name="tax_copilot"),
    path("personality/", views.money_personality_view, name="money_personality"),
    path("goal-simulator/", views.goal_simulator_view, name="goal_simulator"),
    path("social-proof/", views.social_proof_view, name="social_proof"),
    path("research/", views.research_view, name="research"),
    path("opportunity-radar/", views.opportunity_radar_view, name="opportunity_radar"),
    path("chart-intelligence/", views.chart_intelligence_view, name="chart_intelligence"),
    path("voice/", views.voice_view, name="voice"),
    path("expenses/", views.expense_analytics_view, name="expense_analytics"),
    path("advisor/", views.advisor_view, name="advisor"),
    path("life-events/", views.life_event_view, name="life_events"),
    path("compliance/", views.compliance_view, name="compliance"),
    path("family/", views.family_view, name="family"),
    path("admin/", views.admin_view, name="admin_dashboard"),
    path("report-card/", views.report_card_view, name="report_card"),
    # API proxy endpoints
    path("api/profile/patch/", views.api_profile_patch, name="api_profile_patch"),
    path("api/profile/upsert/", views.api_profile_upsert, name="api_profile_upsert"),
    path("api/nudges/pending/", views.api_nudges_pending, name="api_nudges_pending"),
    path("api/chat/history/", views.api_chat_history, name="api_chat_history"),
    path("api/agents/money-health/", views.api_agent_money_health, name="api_agent_money_health"),
    path("api/chat/", views.api_chat, name="api_chat"),
    path("api/chat/stream/", views.api_chat_stream, name="api_chat_stream"),
    path("api/voice/", views.api_voice, name="api_voice"),
    path("api/voice/navigate/", views.api_voice_navigate, name="api_voice_navigate"),
    path("api/nudges/<str:nudge_id>/read/", views.api_nudge_read, name="api_nudge_read"),
    path("api/nudges/<str:nudge_id>/read", views.api_nudge_read, name="api_nudge_read_no_slash"),
    path("api/nudges/mark-all-read/", views.api_nudge_mark_all_read, name="api_nudge_mark_all_read"),
    # Export proxy endpoints
    path("api/export/<str:export_type>/csv/", views.api_export_proxy, {"fmt": "csv"}, name="api_export_csv"),
    path("api/export/<str:export_type>/pdf/", views.api_export_proxy, {"fmt": "pdf"}, name="api_export_pdf"),
    path("api/budget/expense/", views.api_budget_expense, name="api_budget_expense"),
    path("api/goals/create/", views.api_goals_create, name="api_goals_create"),
    path("api/goals/funds/", views.api_goals_funds, name="api_goals_funds"),
    path("api/goals/link/", views.api_link_funds, name="api_link_funds"),
]
